export const DASHBOARD2_GET_EXERCISE_REQUEST = "DASHBOARD2_GET_EXERCISE_REQUEST";
export const DASHBOARD2_GET_EXERCISE_SUCCESS = "DASHBOARD2_GET_EXERCISE_SUCCESS";
export const DASHBOARD2_GET_EXERCISE_ERROR = "DASHBOARD2_GET_EXERCISE_ERROR";
