export const DASHBOARD_GET_EXERCISE_REQUEST = "DASHBOARD_GET_EXERCISE_REQUEST";
export const DASHBOARD_GET_EXERCISE_SUCCESS = "DASHBOARD_GET_EXERCISE_SUCCESS";
export const DASHBOARD_GET_EXERCISE_ERROR = "DASHBOARD_GET_EXERCISE_ERROR";
